### ISSUE TITLE
unique roles for student and teacher

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#127]
differentiate upon logging in

**Comment by eemshi** [comment]
- remove facebook login
- for first time logins (based on email address), go to first-time view
  - are you a teacher or student?
  - ???
- associate role to user account
-

**Comment by tylerperkins** [comment]
_Regarding handling of duplicates:_ This is generally a difficult problem, since you have to decide -- or provide a way for the user to decide -- which bits and pieces of their saved state from the two accounts they want to keep. The best strategy is to prevent duplicates from happening in the first place. I think we can check the email address of a new user, and if there's a match with an existing account, then refresh the existing account's Firebase token and use that account, or redirect them to sign in as the existing user. If one user uses two different email addresses or Google accounts, all bets are off!

_As to "investigate":_ I experimented, and it looks like the answer to the first question is yes. The  actual login/signup is handled by Auth0, and I've seen no docs mentioning any resolution of email addresses. I wouldn't expect otherwise, since login by email is a process on _their_ server, while login through another provider is delegated to the _provider_. Such a feature would be kind of special, mostly benefiting Google users, since not all login providers have email servers. Nonetheless, as I mentioned above, we could do our own check of email addresses to force the first account to be used.

_Regarding the second "investigate" question:_ Is this possible? Unless the app has a bug, you won't be able to bring up the modal to sign in once you've logged in. The button changes to "Log out".

**Comment by eemshi** [comment]
Hi @tylerperkins, I worded that unclearly - it should be more like:
if you log in through the google button once (since it lets you do that without signing up), and then, in a different session, do an email sign up with the same google email address, does it create a new user record?

**Comment by tylerperkins** [comment]
OK. The answer to that too is _yes_, as above.
